
# Pull the minimal Ubuntu image
FROM ubuntu

#Add discription in label
LABEL maintainer="sultandev45 <mubashersultanmehmood@gmail.com>"
LABEL description="This Dockerfile installs nginx server using base image ubuntu and host wep-app."

#mantainer email Add detail in image
MAINTAINER Mubasher Sultan Mehmood < mubashersultanmehmoodgmail.com >

# Install Nginx
RUN apt-get -y update && apt-get -y install nginx

# Copy the Nginx config
COPY default /etc/nginx/sites-available/default
#Copy website
ADD ./Keyboard /usr/share/nginx/html
# Expose the port for access
EXPOSE 80/tcp

# Run the Nginx server
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
