
# Pull the minimal Ubuntu image
FROM ubuntu

#Add discription in label
LABEL maintainer="sultandev45 <mubashersultanmehmood@gmail.com>"
LABEL description="This Dockerfile installs nginx server using base image ubuntu and host wep-app."

#mantainer email Add detail in image
MAINTAINER Mubasher Sultan Mehmood < mubashersultanmehmoodgmail.com >

# Install Nginx
RUN apt-get -y update && apt-get -y install nginx

# Copy the Nginx config
COPY default /etc/nginx/sites-available/default

#Copy website

#Install git
RUN apt-get -y install git

#Clone repository from git hub
RUN git clone https://github.com/sultandev45/web01.git

#Copy site from host to server directory
#ADD ./Keyboard /usr/share/nginx/html

#Move clone repository from container to server Directory
RUN mv ./web01/Keyboard/* /var/www/html/

# Expose the port for access
EXPOSE 80/tcp

# Run the Nginx server
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
